# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actio

name: Fast-API CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test python Code
      run: | 
        pip3 install -r requirements.txt 
        cd app/
        pytest
      
  build-push-container:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker build -t lokilone/fast-api:${GITHUB_SHA} .
        docker tag  lokilone/fast-api:${GITHUB_SHA} lokilone/fast-api:latest
        docker images
        docker run -d -p 80:80 --name fastapi lokilone/fast-api:${GITHUB_SHA}
        sleep 10
        docker login -u ${{ secrets.REGISTRY_USER  }} -p ${{ secrets.REGISTRY_PASSWD  }}
        docker push lokilone/fast-api:${GITHUB_SHA}
        docker push lokilone/fast-api:latest

  deploy:
    needs: build-push-container
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME  }}
        username: ${{ secrets.USER_NAME  }}
        key: ${{ secrets.AWS_PRIVATE_KEY  }}
        port: 22
        script: |
          sudo docker rm -f fastapi 
          sudo docker rmi lokilone/fast-api:latest
          sleep 10 
          sudo docker run -d -p 9000:80 --name fastapi lokilone/fast-api:latest
          sudo docker ps 
          sleep 10 
          curl localhost:9000
          ls 
          sudo docker images
